### ISSUE TITLE
please add user registration page

### ISSUE THREAD

**Issue by sensasi-delight** [BayuDC/warnetku#6]
can't login on fresh install/initial deployment

**Comment by BayuDC** [comment]
I can't do that, because this is an internal website, so everything is controlled by admin. The are several default users that you can use for login. For example, username: operator0, password: operator0. And also don't forget to seed the database `php artisan migrate --seed`

**Comment by sensasi-delight** [comment]
so the data on seeder is the initial state of the app and not for demo only?
